name: Delete old releases

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}